version: '3.4'

services:
  nifi-management-server-rnd:
    container_name: nifi-management-server-rnd
    image: peterbak/nifi-management-server
    build:
      context: ./nifi-management-server
      target: debug
    restart: on-failure
    environment:
      - SERVER_NAME=NifiManagementRndContainer
      - SERVER_PORT=8880
    volumes:
      - ./nifi-management-server/src/:/app/src/ #debug src
      - D:\Docker\Data\nifi-management-data:/app/data
    ports:
      - 5002:5000
      - 9229:9229 #debug port
    networks:
      - rnd

networks:
  rnd:
