version: '3.4'

services:
  # rnd
  nifi-management-server-rnd:
    container_name: nifi-management-server-rnd
    image: peterbak/nifi-management-server
    build:
      context: ./nifi-management-server
      target: debug
    restart: on-failure
    environment:
      - SERVER_NAME=NifiManagementRnd
      - SERVER_PORT=8880
      - NIFI_HOST= http://nifi-rnd:8080
      - NIFI_REGISTRY_HOST=http://registry-rnd:18080
    volumes:
      - ./nifi-management-server/src/:/app/src/ #debug src
      - D:\Docker\Data\nifi-management-data:/app/data
    ports:
      - 8880:8880
      - 9228:9229 #debug port
    networks:
      - rnd

  nifi-rnd:
    image: 'apache/nifi:latest'
    restart: on-failure
    depends_on:
      - nifi-management-server-rnd
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=Aa123456!Aa123456!
      - NIFI_VARIABLE_REGISTRY_PROPERTIES=./custom-properties/props2.properties
      # - NIFI_WEB_HTTPS_PORT=8443
      - NIFI_WEB_HTTP_PORT=8080
    ports:
      # - 8443:8443
      - 8080:8080
      # - 8090:8090
    volumes:
      - D:\Docker\Data\nifi\nifi-registry-poc\rnd\database_repository:/opt/nifi/nifi-current/database_repository
      - D:\Docker\Data\nifi\nifi-registry-poc\rnd\flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - D:\Docker\Data\nifi\nifi-registry-poc\rnd\content_repository:/opt/nifi/nifi-current/content_repository
      - D:\Docker\Data\nifi\nifi-registry-poc\rnd\provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - D:\Docker\Data\nifi\nifi-registry-poc\rnd\state:/opt/nifi/nifi-current/state
      - D:\Docker\Data\nifi\nifi-registry-poc\rnd\logs:/opt/nifi/nifi-current/logs
      # uncomment the next line after copying the /conf directory from the container to your local directory to persist NiFi flows
      # run command in bind mount folder:
      #     docker cp <container-name>:/opt/nifi/nifi-current/conf D:\Docker\Data\nifi\nifi-registry-poc\rnd\conf
      - D:\Docker\Data\nifi\nifi-registry-poc\rnd\conf:/opt/nifi/nifi-current/conf
      # folder for user source
      - D:\Docker\Data\nifi\nifi-registry-poc\rnd\_source:/opt/nifi/nifi-current/source
      # folder for user target
      - D:\Docker\Data\nifi\nifi-registry-poc\rnd\_target:/opt/nifi/nifi-current/target
      # folder for temp data
      - D:\Docker\Data\nifi\nifi-registry-poc\rnd\_temp-data:/opt/nifi/nifi-current/temp-data
    networks:
      - rnd

  registry-rnd:
    image: 'apache/nifi-registry:latest'
    restart: on-failure
    depends_on:
      - nifi-management-server-rnd
    ports:
      - 18080:18080
    volumes:
      # uncomment the next line after copying the /conf directory from the container to your local directory to persist Nifi-Regsitry data
      # run command in bind mount folder:
      #     docker cp <container-name>:opt/nifi-registry/nifi-registry-current/conf D:\Docker\Data\nifi-registry\nifi-registry-poc\rnd\conf
      - D:\Docker\Data\nifi-registry\nifi-registry-poc\rnd\conf:/opt/nifi-registry/nifi-registry-current/conf
      - D:\Docker\Data\nifi-registry\nifi-registry-poc\rnd\flow-storage:/opt/nifi-registry/nifi-registry-current/flow_storage
      - D:\Docker\Data\nifi-registry\nifi-registry-poc\rnd\database:/opt/nifi-registry/nifi-registry-current/database
    networks:
      - rnd

  # production
  nifi-management-server-production:
    container_name: nifi-management-server-production
    image: peterbak/nifi-management-server
    build:
      context: ./nifi-management-server
      target: debug
    restart: on-failure
    environment:
      - SERVER_NAME=NifiManagementProduction
      - SERVER_PORT=8890
      - NIFI_HOST= http://nifi-production:8090
      - NIFI_REGISTRY_HOST=http://registry-production:18090
    volumes:
      - ./nifi-management-server/src/:/app/src/ #debug src
      - D:\Docker\Data\nifi-management-data:/app/data
    ports:
      - 8890:8890
      - 9229:9229 #debug port
    networks:
      - production

  nifi-production:
    image: 'apache/nifi:latest'
    restart: on-failure
    depends_on:
      - nifi-management-server-production
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=Aa123456!Aa123456!
      - NIFI_VARIABLE_REGISTRY_PROPERTIES=./custom-properties/props2.properties
      # - NIFI_WEB_HTTPS_PORT=8443
      - NIFI_WEB_HTTP_PORT=8090
    ports:
      # - 8443:8443
      - 8090:8090
      # - 8090:8090
    volumes:
      - D:\Docker\Data\nifi\nifi-registry-poc\production\database_repository:/opt/nifi/nifi-current/database_repository
      - D:\Docker\Data\nifi\nifi-registry-poc\production\flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - D:\Docker\Data\nifi\nifi-registry-poc\production\content_repository:/opt/nifi/nifi-current/content_repository
      - D:\Docker\Data\nifi\nifi-registry-poc\production\provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - D:\Docker\Data\nifi\nifi-registry-poc\production\state:/opt/nifi/nifi-current/state
      - D:\Docker\Data\nifi\nifi-registry-poc\production\logs:/opt/nifi/nifi-current/logs
      # uncomment the next line after copying the /conf directory from the container to your local directory to persist NiFi flows
      # run command in bind mount folder:
      #     docker cp <container-name>:/opt/nifi/nifi-current/conf D:\Docker\Data\nifi\nifi-registry-poc\production\conf
      - D:\Docker\Data\nifi\nifi-registry-poc\production\conf:/opt/nifi/nifi-current/conf
      # folder for user source
      - D:\Docker\Data\nifi\nifi-registry-poc\production\_source:/opt/nifi/nifi-current/source
      # folder for user target
      - D:\Docker\Data\nifi\nifi-registry-poc\production\_target:/opt/nifi/nifi-current/target
      # folder for temp data
      - D:\Docker\Data\nifi\nifi-registry-poc\production\_temp-data:/opt/nifi/nifi-current/temp-data
    networks:
      - production

  registry-production:
    image: 'apache/nifi-registry:latest'
    restart: on-failure
    depends_on:
      - nifi-management-server-production
    environment:
      - NIFI_REGISTRY_WEB_HTTP_PORT=18090
    ports:
      - 18090:18090
    volumes:
      # uncomment the next line after copying the /conf directory from the container to your local directory to persist Nifi-Regsitry data
      # run command in bind mount folder:
      #     docker cp <container-name>:opt/nifi-registry/nifi-registry-current/conf D:\Docker\Data\nifi-registry\nifi-registry-poc\production\conf
      - D:\Docker\Data\nifi-registry\nifi-registry-poc\production\conf:/opt/nifi-registry/nifi-registry-current/conf
      - D:\Docker\Data\nifi-registry\nifi-registry-poc\production\flow-storage:/opt/nifi-registry/nifi-registry-current/flow_storage
      - D:\Docker\Data\nifi-registry\nifi-registry-poc\production\database:/opt/nifi-registry/nifi-registry-current/database
    networks:
      - production

networks:
  rnd:
  production:
